### ISSUE TITLE
Compatibility of damage model types

### ISSUE THREAD

**Issue by raoanirudh** [GEMScienceTools/rmtk_docs#13]
The manual does not clarify which damage model types are compatible with the different methodologies. There should ideally be a table in §4.2.3 summarising this information, and the description sections of each methodology should also mention the compatible damage model types.

If the owners of each methodology can provide this info in the comments here, I can add the text to the relevant sections.

**Comment by ccasotto** [comment]
SPO2IDA, Dolsek and Fajfar 2004, and Ruiz-Garcia and Miranda 2007 all use inter-storey drift based damage model.
