### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by ccasotto** [GEMScienceTools/rmtk_docs#16]
Bibliography should be harmonised

**Comment by raoanirudh** [comment]
Chiara pointed out that some of the references are missing the names of the authors. Specifically, the following two references need to be corrected:

— (2008b).“Simplified pushover-based vulnerability analysis for large-scale assessment of RC buildings”. In: Engineering Structures 30, pages 804–820 (cited on pages 34, 35, 39, 43, 44).

— (2014c).“Investigation of the characteristics of Portuguese regular moment-frame RC buildings and development of a vulnerability model”. In: Bulletin of Earthquake Engineering (cited on pages 34, 36).

**Comment by raoanirudh** [comment]
Also, some of the references use the full first and last names of the authors, others just use the last name and initials.
